authors:
  Anas:
    name: Anas Rabhi
    description: Consultant IA & Data Scientist Freelance
    avatar: https://avatars.githubusercontent.com/anas-rabhi
    url: /
    social:
      linkedin: https://www.linkedin.com/in/anasrabhi
      github: https://github.com/anas-rabhi
      twitter: https://x.com/anas9r
